spring:
  application:
    name: demo-hexagonal-application
  profiles:
    active: local
    default: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
  compression:
    enabled: true
    mime-type: application/json, application/xml, text/html, text/xml, text/plain
  servlet:
    context-path: /context-path
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: beans, caches, conditions, configprops, health, loggers, metrics, mappings, threaddump, prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  server:
    port: 8081
    context-path: /
  security:
    enabled: false